FROM ubuntu:24.04

ARG USERNAME=pfe_user
ENV SSH_USER=${USERNAME}

ARG CACHEBUST=1
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		openssh-server \
		jq \
		rsyslog \
		curl \
		ca-certificates \
		gnupg \
	&& curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg \
		| tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null \
	&& curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list \
		| tee /etc/apt/sources.list.d/tailscale.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends tailscale \
	&& rm -rf /var/lib/apt/lists/* \
	&& mkdir -p /var/run/sshd \
	&& useradd -m -s /bin/bash ${USERNAME} \
	&& sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config \
	&& sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
	&& sed -i 's/^#\?UsePAM.*/UsePAM yes/' /etc/ssh/sshd_config \
	&& echo "AllowUsers ${USERNAME}" >> /etc/ssh/sshd_config

RUN apt update && apt install -y lsb-release && apt install -y wget 
RUN wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.14.4-1_amd64.deb


COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 22
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]