services:
  ssh-cible:
    container_name: ssh-cible
    build:
      context: .
      dockerfile: DockerFile
      args:
        USERNAME: ${SSH_USERNAME:-pfe_user}
    environment:
      SSH_PASSWORD: ${SSH_PASSWORD:-PFE2026!}
    restart: unless-stopped
    networks:
      - internal-ssh-net # Réseau totalement isolé
networks:
  internal-ssh-net:
    internal: false       # Ce réseau n'a pas accès à Internet
